[tool.black]
target-version = ['py310']

[tool.pytest.ini_options]
cache_dir = "/dev/shm/pytest_cache"
filterwarnings = [
    "ignore::DeprecationWarning:flatbuffers.*:",
    "ignore::DeprecationWarning:keras.*:",
    "ignore::DeprecationWarning:keras_preprocessing.*:",
    "ignore::DeprecationWarning:tensorflow.*:",
]
