[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black" 

[tool.pytest.ini_options]
cache_dir = "/dev/shm/pytest_cache"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]
filterwarnings = [
    "ignore::DeprecationWarning:flatbuffers.*:",
    "ignore::DeprecationWarning:keras.*:",
    "ignore::DeprecationWarning:keras_preprocessing.*:",
    "ignore::DeprecationWarning:tensorflow.*:",
]
