FROM python:3.10.2-slim-bullseye

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
    git \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pip-compile-multi
