FROM nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04
RUN --mount=type=bind,source=.gge_build_cache/Miniforge3.sh,target=/Miniforge3.sh /bin/bash /Miniforge3.sh -b
ENV PATH=/root/miniforge3/bin:$PATH

SHELL ["/bin/bash", "-c", "-i"]
RUN conda init bash
RUN conda activate
RUN conda install python=3.10

COPY ./requirements/ /requirements/
RUN pip install -r /requirements/test.txt --no-cache-dir

COPY ./pyproject.toml /gge/
COPY ./data /gge/data/
COPY ./gge /gge/gge/
