channels:
  - conda-forge
dependencies:
  - python
  - pip
  - graphviz
  - pip:
    - black
    - flake8
    - mypy
    - pip-compile-multi
    - attrs
    - h5py
    - hypothesis
    - lark
    - loguru
    - networkx
    - pillow
    - pydot
    - pytest
    - pytest-pspec
    - scipy
    - tensorflow-gpu
    - typer

